all:
	C:\dev\qt-4.8.4-vs11-lib64\bin\qmake C:/dev/qt-everywhere-opensource-src-4.8.4/translations\translations.pro  -o Makefile -spec win32-msvc2012
	"$(MAKE)" -$(MAKEFLAGS) -f Makefile
first: all
qmake:
	C:\dev\qt-4.8.4-vs11-lib64\bin\qmake C:/dev/qt-everywhere-opensource-src-4.8.4/translations\translations.pro  -o Makefile -spec win32-msvc2012
